#!/bin/bash

echo $1

case $1 in
    setup) 
        g++ -std=c++14 api.cpp `pkg-config --libs --cflags opencv` -o api
        ./api 1 2 > train.txt
    ;;
    train)
      echo "todo"  
    ;;
    exec)
        ./api 1 > input.txt
    ;;
esac